FROM marathon-cloud-run-sample-docker-base

##############################################################################
# python packages
##############################################################################

WORKDIR /app
COPY docker/poetry.lock docker/pyproject.toml /app/
RUN poetry config virtualenvs.create false && poetry install --no-interaction

RUN echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] http://packages.cloud.google.com/apt cloud-sdk main" | tee -a /etc/apt/sources.list.d/google-cloud-sdk.list && curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | apt-key --keyring /usr/share/keyrings/cloud.google.gpg  add - && apt-get update -y && apt-get install google-cloud-sdk -y

##############################################################################
# files
##############################################################################
ARG PROJECT_ID
ENV PROJECT_ID=$PROJECT_ID

COPY docker/run.py /app/startup/
COPY docker/server.py /app/startup/
COPY docker/server.sh /app/startup/
COPY docker/env.py /app/startup/
WORKDIR /app/startup
